services:
  prism-insight:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prism-insight-container
    image: prism-insight:latest
    
    # 환경 변수
    environment:
      - TZ=Asia/Seoul
      - PYTHONUNBUFFERED=1
    
    # 볼륨 마운트
    volumes:
      # 데이터 영속성을 위한 볼륨
      - ./data:/app/prism-insight/data
      - ./stock_tracking_db.sqlite:/app/prism-insight/stock_tracking_db.sqlite
      - ./reports:/app/prism-insight/reports
      - ./pdf_reports:/app/prism-insight/pdf_reports
      - ./html_reports:/app/prism-insight/html_reports
      - ./charts:/app/prism-insight/charts
      - ./telegram_messages:/app/prism-insight/telegram_messages
      
      # 설정 파일 (호스트에서 수정 가능)
      - ./.env:/app/prism-insight/.env
      - ./mcp_agent.config.yaml:/app/prism-insight/mcp_agent.config.yaml
      - ./mcp_agent.secrets.yaml:/app/prism-insight/mcp_agent.secrets.yaml
      
      # 로그 파일
      - ./logs:/app/prism-insight/logs
    
    # 작업 디렉토리
    working_dir: /app/prism-insight
    
    # 컨테이너 시작 시 실행할 명령어 (백그라운드 유지)
    command: tail -f /dev/null
    
    # 재시작 정책
    restart: unless-stopped
    
    # 네트워크 모드
    network_mode: bridge
    
    # 헬스체크
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# 볼륨 정의 (선택사항)
volumes:
  prism-data:
    driver: local
